### ISSUE TITLE
World Load Hangup on Broken Script

### ISSUE THREAD

**Issue by Tedyhere** [codetaylor/advancedmortars#22]
Could you add a check for broken recipe, currently if you misspell anything or forget a , " [] () or ; the world hangs up on load due to a null pointer exception the the Mortar recipe handler.
https://pastebin.com/r1AdGQZZ

Makes it very hard to find what I did wrong.

Here is the script..
https://pastebin.com/kPFSMhCb

**Comment by codetaylor** [comment]
I'm working on adding some checks to prevent the NPE you described. I am unable to fully replicate your problem because I don't have Silent's Gems or your custom ContentTweaker content.

In the meantime, I do notice that in some places you have `<contenttweaker:white:dye>` and others `<contenttweaker:white_dye>`. That might be the source of your problem.

CraftTweaker probably errors on parsing the `<contenttweaker:white:dye>` and returns a null.

I'll see if I can't replicate the behavior using a bracket handler like that.

Did this error happen on a server?

**Comment by codetaylor** [comment]
My theory was correct and I was able to replicate the problem you've described.

Using this script:
```
import mods.advancedmortars.Mortar;
import crafttweaker.item.IItemStack;

//Green Dye
Mortar.addRecipe(["wood", "stone"], <minecraft:dye:2>, 10, [<minecraft:dye:white>]);
```

Crash:
https://gist.github.com/codetaylor/e64362a829e4c65b2c578b955e9c72f9

**Comment by codetaylor** [comment]
Ok, this is better.

It will now fully load and display this in the console:
![image](https://user-images.githubusercontent.com/1240716/34473647-39350782-ef2a-11e7-8ab7-71417df96aeb.png)

As well as display this in the `crafttweaker.log` file:
```
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Building registry
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Successfully built item registry
[INITIALIZATION][CLIENT][INFO] Loading scripts
[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: mortar.zs}
[INITIALIZATION][CLIENT][ERROR] mortar.zs:5: Could not resolve <minecraft : dye : white>
[AVAILABLE][CLIENT][INFO] Altering mods.advancedmortars.Mortar Recipe(s) for <minecraft:dye:2>
[AVAILABLE][CLIENT][ERROR] Unknown input type: null
[SERVER_STARTED][CLIENT][INFO] Fixed the RecipeBook
```

**Comment by codetaylor** [comment]
Fixed in 1.6.15

**Comment by codetaylor** [comment]
Build 1.6.15 submitted to CurseForge.

**Comment by Tedyhere** [comment]
Thanks for the quick response, I ended up fixing the script errors, but yeah having it spit out the errored line would be preferrable. Thanks for the quick response.  Love the mod, as well as your Artisan Tables one
