### ISSUE TITLE
Add in Gold Mortar

### ISSUE THREAD

**Issue by DWX12** [codetaylor/advancedmortars#41]
Going through alot of mods, there's a trend to stick with vanilla standards when it comes to its progression and, while this mod follows most of it, it leaves out one type of mortar, gold. I could ask for obsidian and possibly emerald too, as chest and other mods go that route, but I'm humbly ask for a gold mortar to finish off the set.

Thank you for all the time, work, and effort put into making this cool little mod. I look forward to seeing things I can do with it.

**Comment by codetaylor** [comment]
The player value (PV) of gold tools in vanilla Minecraft is the increased enchantability at the cost of durability. Since the mortars aren't enchantable, though, what would be the PV for a gold mortar? It seems to me that it would just be a mortar with low durability that can be crafted with a rare material. Adding an obsidian or emerald mortar feels more justified as it would add more PV in the form of increased durability. I fail to see the PV in adding a gold mortar, though.

Help me understand: How would you use a gold mortar? What is your use case?

**Comment by DWX12** [comment]
I understand from your point of view why there doesn't seem to be a point to add in a gold mortar, but I guess my case is that you intended this mod to be used in mod packs, which opens up the use of each mortar for various purposes. Sure the durability would be somewhere between stone and iron, but it would be up to the pack maker to decide what its function would be.

Personally, it's more about set collection or rather having a full set of main vanilla materials. Furthermore, you could add in all the different wood and stone skins like other mods have done, but that just seems a bit much. But that's not what I'm asking. Plus, it would look nice for aesthetic purposes.

**Comment by codetaylor** [comment]
Feature available in 1.12.2-1.7.0

**Comment by DWX12** [comment]
Thank you very for the addition and for just listening to those that use your mod, in general.
