### ISSUE TITLE
[Suggestion] Remove Modes

### ISSUE THREAD

**Issue by Tetrajak** [codetaylor/advancedmortars#8]
The existence of modes that must be controlled by the user is redundant, as the distinction is already made by the inserted ingredients. Is there even a use case where the same ingredients produce different results depending on the mode? For these reasons, I recommend removing modes entirely from the mod.

**Comment by codetaylor** [comment]
Well, shit.

You make a valid argument against the existence of modes.

If modes were eliminated, the behavior of the two modes could be merged. Instead it would allow up to eight stacks of items to be inserted. This would simplify the operation of the mortar as well as allow the player to do more than one multiple-ingredient craft without having to refill the thing.

I think this would improve the mod in more than one way.

Thanks for pointing this out to me.

**Comment by Tetrajak** [comment]
You're welcome, I'm glad my suggestion helps!

**Comment by codetaylor** [comment]
I have given this some more thought.

If the modes were eliminated and merged in the way that I talked about earlier, it could lead to recipe conflicts. For example if there were two recipes configured, one that took one bone meal and one red dye to produce a magenta dye and another that took two bone meal and one red dye to produce a pink dye, there would be a recipe conflict. 

In a traditional crafting grid gui, one in which the player can explicitly place items in slots, the system could easily distinguish between the two recipes if the two bone meal in the second recipe were split into two different crafting slots. With the way that the mortar works, however, the player has no control over which slot the items go into. 

This means that if implemented as described previously, allowing all eight slots to hold full stacks, both bone meal items would go into the same slot and the system would not be able to tell if the player's intent is to craft the magenta dye using one bone meal item or to craft the pink dye using both bone meal items. 

The existence of the mixing mode precludes recipe conflicts of this nature, while the crushing mode, which exposes only one slot that holds a full stack, reduces the monotony of having to place a single item in the mortar each time a single-item craft is performed.

It could be argued that, since the mod provides only two example recipes, recipe conflicts are the onus of the recipe or pack designer and that the example conflict I gave could easily be remedied by changing one of the recipes.

I'm not fully convinced that eliminating modes is the way to go, however I recognize that the only use case I can muster is an edge case to prevent error in third-party configuration. Therefore, I'm also not fully convinced that supporting this edge case is worth keeping both modes, effectively doubling the complexity of the mod and the effort of the player.

**Comment by Tetrajak** [comment]
A counter point to your argument about recipe conflict is that the mod can default to a recipe that has the higher number of ingredients, and that if there are multiple ingredients in the mortar that each have their own recipes and none are dominant, none of them are processed (the same behaviour as a crafting table).

As for third-party config conflicts; that's something a modpack creator can resolve by tweaking the config (I hope), the same way they resolve conflicts in other modded machines and crafting recipes. It's also worth noting that the modes do not eliminate this problem; consider the mods Roots, NetherEx, and Quark; they all have their own dusts made from wither skulls, and modes would not resolve a conflict if all 3 recipes were entered with the same single ingredient. It is also worth noting that adding more modes to resolve this example would only compound usability issues.

**Comment by codetaylor** [comment]
> A counter point to your argument about recipe conflict is that the mod can default to a recipe [...]

I believe that this would be the way to go. For the sake of efficiency, it should probably default to the first matched recipe, ie. the first recipe for which all ingredients are satisfied by the items in the mortar.

I now stand convinced. Removal of the modes can be expected in the next significant update.

Thanks again for bringing this up and having this discussion with me. :)

**Comment by Tetrajak** [comment]
You're most welcome, I am glad for the constructive discourse we've had, and look forward to adding the updated mod to my personal modpack :)

**Comment by codetaylor** [comment]
Completed in faafa3f.
